---
# ----------------------------------------------------------------------
# Configurazioni di Base (Flags per includere/escludere sezioni)
# ----------------------------------------------------------------------
titlepage: true
headerfooter: true
draft: false
toc: true
listfigures: false
listtables: false

# ----------------------------------------------------------------------
# Dati Aziendali e Documento
# ----------------------------------------------------------------------
CompanyProject: MHQ.PSA.VAR0000199
CompanyDepartment: CCS MNC LSH3
CompanyOffice: QG
CompanyDesigner: Benetti Fabio
CompanyDesignerCode:
CompanyTechnicalManager:
CompanyTechnicalSupervisor: Antonio De Renzis
CompanyStudyTitle: P3IF High Speed UDP Pkt Description
CompanyDocumentCode: BSV000F0035F

# ----------------------------------------------------------------------
# Impostazioni di Layout e Assets
# ----------------------------------------------------------------------
LogoFileName: '../assets/docfiles/logo-marposs.eps'
footerText: 'RISERVATO - PROPRIETÃ€ DI Marposs S.p.A.'

# ----------------------------------------------------------------------
# Configurazione Watermark (se draft: true)
# ----------------------------------------------------------------------
watermark_text: 'Draft'

# ----------------------------------------------------------------------
# Configurazioni TOC
# ----------------------------------------------------------------------
tocDepth: 5
---

