# ----------------------------------------------------------------------
# ATTENZIONE: Questo file YAML deve contenere ESCLUSIVAMENTE
# opzioni da riga di comando di Pandoc (i.e. --option) e NON i percorsi
# a template o filtri Lua.
# Per template e filtri Lua, utilizza i comandi appositi della tua architettura.
# ----------------------------------------------------------------------

# Opzione per trattare i titoli di primo livello come capitoli.
top-level-division: chapter
# Opzione per abilitare il pacchetto 'listings' per la formattazione del codice in LaTeX.
listings: true
pdf-engine: xelatex
